dotenv:
    enabled: true
spring:
  application:
    name: bank-application
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
  #flyway:
  #  baseline-on-migrate: true
  #  url: jdbc:mysql://localhost:3306/eazybank
  #  user: isra
  #  password: C0ntr4s3ñ44321
server:
  port: 8081